Setup database
LouisLagrange1/Instamint-SDV pull request #2
Opened 2024-05-03 15:06 UTC by LouisLagrange1

In this branch I have setup the connection to the database.

I used knex to do the migrations, the models and the seed

2024-05-03 15:17 UTC, meyer0x requested changes
Pourquoi les models ne sont pas rempli ?

2024-05-03 15:17 UTC, meyer0x commented on knexfile.js
> +    database: process.env.DB__CONNECTION__DATABASE,
Mettre DB_**_

2024-05-03 15:17 UTC, meyer0x commented on src/api/db/migrations/20240503131204_profiles.js
> +        table.text("type").notNullable();
C'est quoi "type" ?

2024-05-03 15:17 UTC, meyer0x commented on src/api/db/migrations/20240503131204_profiles.js
> +        table.text("bio").notNullable();
Tu es sur que la bio est not nullable ?

2024-05-03 15:17 UTC, meyer0x commented on src/api/db/migrations/20240503131254_minters.js
> +        table.text("type").notNullable();
Pareille, c'est quoi type ?

2024-05-03 15:21 UTC, LouisLagrange1 commented on knexfile.js
> +    database: process.env.DB__CONNECTION__DATABASE,
C'est fait

2024-05-03 15:21 UTC, LouisLagrange1 commented on src/api/db/migrations/20240503131204_profiles.js
> +        table.text("type").notNullable();
J'ai suivi le schema de Theo

2024-05-03 15:21 UTC, LouisLagrange1 commented on src/api/db/migrations/20240503131204_profiles.js
> +        table.text("bio").notNullable();
J'ai suivi le schema de Theo

2024-05-03 15:21 UTC, LouisLagrange1 commented on src/api/db/migrations/20240503131254_minters.js
> +        table.text("type").notNullable();
J'ai suivi le schema de Theo

2024-05-03 15:26 UTC, meyer0x approved these changes

2024-05-03 15:26 UTC, merged

2024-05-05 16:24 UTC, IoOziT reviewed
Not all models have been reviewed (some are missing the relations).
Models still to be reviewed:

1. Minter
2. Profile
3. Teabag
4. Report
5. Nft
6. Notification

About migrations:
Most of the changes suggested are column type change.
The are some junction tables missing. It's on me, they were implied in the schema I gave but not shown.

2024-05-05 16:24 UTC, IoOziT commented on src/api/db/migrations/20240503131204_profiles.js
Junction for follows is missing.

```javascript
module.exports = {
  async up(knex) {
    await knex.schema.createTable("followers", (table) => {
      table.integer("follower_id").references("id").inTable("profiles").notNullable();
      table.integer("followed_id").references("id").inTable("profiles").notNullable();
      table.primary(["follower_id", "followed_id");
      table.check("?? != ??", ["follower_id", "profile_id"]);
    })
  },
  async down(knex) {
    await knex.schema.dropTable("followers");
  }
}

2024-05-05 16:24 UTC, IoOziT commented on src/api/db/migrations/20240503131433_likes.js
> +        table.timestamps(true, true);
Needs a constraint to ensure a NFT can't be liked twice by the same person.

```javascript
table.primary(["minter_id", "nft_id"]);
```

2024-05-05 16:24 UTC, IoOziT commented on src/api/db/models/MintersModel.js
File name should be in camel case (first word is lowercase, following words start with an uppercase).
Including `Model` in the name of the class is unnecessary because the model is in a `models` folder.
Relations are missing.

```javascript
import BaseModel from "@/api/db/models/BaseModel.js";
import Teabag from "./teabag.js";
import Profile from "./profile.js";
import Comment from "./comment.js";
import Notification from "./notification.js";
import Report from "./report.js";
import Nft from "./nft.js";
import Like from "./like.js";
import Mention from "./mention.js";

class Minter extends Profile {
  static tableName = "minters";
  static relationMappings = {
      ...Profile.relationMappings,
      // TO FINISH
    }
  }
}

export default Minter
```

2024-05-05 19:36 UTC, IoOziT commented on src/api/db/models/MentionsModel.js
I just realised that the `mentions` table is a junction table and doesn't need its own model.
This file should be deleted.

2024-05-05 19:44 UTC, IoOziT commented on src/api/db/migrations/20240503131307_nfts.js
> +        table.increments("id").primary();
The reference to the profile owning this NFT (minter or teabag) is missing.
Add the following line below:

```javascript
table.integer("profile_id").references("id").inTable("profiles').notNullable();
```

2024-05-05 19:47 UTC, IoOziT commented on src/api/db/models/ProfilesModel.js
File name should be in camel case (first word is lowercase, following words start with an uppercase).
Including `Model` in the name of the class is unnecessary because the model is in a `models` folder.
Relations are missing.

```javascript
import BaseModel from "./baseModel.js";
import Comment from "./comment.js";

class Profile extends BaseModel {
  static tableName = "profiles";
  static relationMappings = {
    followers: {
      relation: BaseModel.ManyToManyRelation,
      modelClass: Profile,
      join: {
        from: "minters.id",
        through: {
          from: "followers.followed_id",
          to: "followers.follower_id"
        },
        to: "profiles.id"
      }
    },
   following: {
      relation: BaseModel.ManyToManyRelation,
      modelClass: Profile,
      join: {
        from: "minters.id",
        through: {
          from: "followers.follower_id",
          to: "followers.followed_id"
        },
        to: "profiles.id"
      }
    },
    mentions: {
      relation: BaseModel.HasManyRelation,
      modelClass: Comment,
      join: {
        from: "profiles.id",
        through: {
          from: "mentions.minter_id",
          to: "mentions.comment_id"
        },
        to: "comments.id"
      }
    },
    nfts: {
      relation: BaseModel.
      modelClass: Nft,
      join: {
        from: "profiles.id",
        to: "nfts.profile_id"
      }
    }
  }
}

export default Profile;

2024-05-05 20:13 UTC, IoOziT commented on src/api/db/migrations/20240503131445_comments.js
> +		table.increments("id").primary();
The relation with the NFT being commented on is missing.
Add the line below:

```javascript
table.integer("nft_id").references("id").inTable("nfts").notNullable();
```

2024-05-05 20:24 UTC, IoOziT commented on src/api/db/models/NftsModel.js
File name should be in camel case (first word is lowercase, following words start with an uppercase).
Including `Model` in the name of the class is unnecessary because the model is in a `models` folder.
Relations are missing.

```javascript
import BaseModel from "./baseModel.js";
import Profile from "./profile.js";
import Comment from "./comment.js";

class Nft extends BaseModel {
  static tableName = "nfts";
  static relationMappings = {
    owner: {
      relation: BaseModel.BelongsToRelation,
      modelClass: Profile,
      join: {
        from: "nfts.owner_id",
        to: "profiles.id"
      }
    },
    comments: {
      relation: BaseModel.HasManyRelation,
      modelClass: Comment,
      join: {
        from: "nfts.id",
        to: "comments.nft_id"
      }
    },
    reactions: {
      relation: BaseModel.HasManyRelation,
      modelClass: Like,
      join: {
        from: "nfts.id",
        to: "likes.nft_id"
      }
    },
    hashtags: {
      relation: BaseModel.
      modelClass: Hashtag,
      join: {
        from: "nfts.id",
        through: {
          from: "nfts_hashtags.nft_id",
          to: "nfts_hashtags.hashtag_id"
        },
        to: "hashtags.id"
      }
    },
    receivedReports: {
      relation: BaseModel.HasManyRelation,
      modelClass: Report,
      join: {
        from: "nfts.id",
        to: "reports.object_id",
        filter: (queryBuilder) => queryBuilder.where("type", "nft")
      }
    }
  }
}

export default Nft;
```

2024-05-05 20:57 UTC, IoOziT commented on src/api/db/models/NotificationsModel.js
File name should be in camel case (first word is lowercase, following words start with an uppercase).
Including `Model` in the name of the class is unnecessary because the model is in a `models` folder.
Relations are missing.

```javascript
import BaseModel from "./baseModel.js";
import Profile from "./profile.js";
import Comment from "./comment.js";
import Nft from "./nft.js";
import Minter from "./minter.js";

class Notification extends BaseModel {
  static tableName = "notifications";
  static relationMappings = {
    minter: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: Minter,
      join: {
        from: "notificatiions.minter_id",
        to: "minters.id"
      }
    },
    nft: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: Nft,
      join: {
        from: "notifications.object_id",
        to: "nfts.id",
        filter: (queryBuilder) => queryBuilder.wherIn("type", ["reply", "comment", "mention", "like"])
      }
    },
    comment: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: Comment,
      join: {
        from: "notifications.object_id",
        to: "comments.id",
        filter: (queryBuilder) => queryBuilder.wherIn("type", ["reply", "comment", "mention"])
      }
    },
    profile: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: Profile,
      join: {
        from: "notifications.object_id",
        to: "profiles..id",
      }
    }
  }
}

export default Notification;
```

2024-05-05 21:04 UTC, IoOziT commented on src/api/db/models/ReportsModel.js
File name should be in camel case (first word is lowercase, following words start with an uppercase).
Including `Model` in the name of the class is unnecessary because the model is in a `models` folder.
Relations are missing.

```javascript
import BaseModel from "./baseModel.js";
import Minter from "./minter.js";

class Report extends BaseModel {
  static tableName = "nfts";
  static relationMappings = {
    minter: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: Minter,
      join: {
        from: "reports.minter_id",
        to: "minters.id"
      }
    },
    nft: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: Nft,
      join: {
        from: "reports.object_id",
        to: "nfts.id",
        filter: (queryBuilder) => queryBuilder.where("type", "nft")
      }
    },
    comment: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: Comment,
      join: {
        from: "reports.object_id",
        to: "comment.id",
        filter: (queryBuilder) => queryBuilder.where("type", "comment")
      }
    },
    profile: {
      relation: BaseModel.BelongsToOneRelation,
      modelClass: Nft,
      join: {
        from: "reports.object_id",
        to: "profiles.id",
        filter: (queryBuilder) => queryBuilder.where("type", "profile")
      }
    }
  }
}

export default Report;
```

2024-05-05 21:11 UTC, IoOziT commented on src/api/db/models/TeabagsModel.js
File name should be in camel case (first word is lowercase, following words start with an uppercase).
Including `Model` in the name of the class is unnecessary because the model is in a `models` folder.
Relations are missing.

```javascript
import BaseModel from "./baseModel.js";
import Profile from "./profile.js";
import Minter from "./minter.js";

class Teabag extends BaseModel {
  static tableName = "teabags";
  static relationMappings = {
    ...Profile.relationMappings,
    memberships: {
      relation: BaseModel.HasManyRelation,
      modelClass: Minter,
      join: {
        from: "teabags.id",
        through: {
          from: "teabag_memberships.teabag_id",
          to: "teabag_memberships.minter_id",
        },
        to: "minters.id"
      }
    }
  }
}

export default Teabag;
```

2024-05-05 21:12 UTC, IoOziT commented on src/api/db/seeds/1-minters.js
Bad formatting (unnecessary newlines and indentation).

2024-05-05 21:13 UTC, IoOziT commented on src/api/db/seeds/2-comments.js
Bad formatting (unnecessary newlines and indentation).

2024-05-05 21:13 UTC, IoOziT commented on src/api/db/seeds/2-comments.js
> +					time: new Date(),
Unnecessary (inserted automatically).

2024-05-05 21:14 UTC, IoOziT commented on src/api/db/seeds/2-comments.js
> +					time: new Date(),
Unnecessary (inserted automatically).

2024-05-05 21:15 UTC, IoOziT commented on src/api/db/seeds/all-hashtags.js
Bad formatting (unnecessary newlines).

2024-05-05 21:15 UTC, IoOziT commented on src/api/db/seeds/all-likes.js
Bad formatting (unnecessary newlines).

2024-05-05 21:16 UTC, IoOziT commented on src/api/db/seeds/all-mentions.js
Bad formatting (unnecessary newlines).

2024-05-05 21:16 UTC, IoOziT commented on src/api/db/seeds/all-nfts.js
Bad formatting (unnecessary newlines).

2024-05-05 21:16 UTC, IoOziT commented on src/api/db/seeds/all-notifications.js
Bad formatting (unnecessary newlines).

2024-05-05 21:17 UTC, IoOziT commented on src/api/db/seeds/all-reports.js
Bad formatting (unnecessary newlines).

2024-05-05 21:17 UTC, IoOziT commented on src/api/db/seeds/all-teabags.js
Bad formatting (unnecessary newlines).

2024-05-05 21:19 UTC, IoOziT commented on src/api/db/migrations/20240503131445_comments.js
> +		table.text("content").notNullable();
Should be of type string with max length of 300.

```javascript
table.string("content", 300).notNullable();
```

2024-05-05 21:20 UTC, IoOziT commented on src/api/db/migrations/20240503131445_comments.js
> +		table.integer("thread_id").references("id").inTable("comments");
Thread ID is not nullable.

```javascript
table.integer("thread_id").references("id").inTable("comments").notNullable();
```

2024-05-05 21:23 UTC, IoOziT reviewed
- Mainly bad column types.
- Files not formatted (2 spaces for JS, not 4 and unnecessary newlines).
- Missing relations in models.
- Some missing junction tables (were implied but not shown explicitly in the schema I gave)

2024-05-06 21:07 UTC, meyer0x commented on src/api/db/migrations/20240503131445_comments.js
> +		table.integer("thread_id").references("id").inTable("comments");
Who we can create the first comments if thread_id refer to the comments table with notNullable ?